# Generated by Django 5.2.1 on 2025-08-05 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Optional subject line', max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Bhautik Gauswami', max_length=100)),
                ('title', models.CharField(default='Machine Learning Engineer', max_length=200)),
                ('email', models.EmailField(default='bhautikgosai4318@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 8141415113', max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Surat', max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(default='395005', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(default="I'm a passionate Machine Learning Engineer with expertise in building intelligent systems that solve real-world problems.", help_text='Biography content')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile photo (recommended: 400x400px)', null=True, upload_to='profile/')),
                ('skills_summary', models.TextField(default='💡 Data Science | 🧠 Deep Learning | 🤖 AI Enthusiast', help_text='Brief skills summary for homepage hero section')),
                ('resume_file', models.FileField(blank=True, help_text='PDF resume file', null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1effc6', help_text='Category color for UI (hex format)', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='Bhautik Gauswami - ML Portfolio', max_length=200)),
                ('site_description', models.TextField(default='Portfolio website of Bhautik Gauswami, Machine Learning Engineer')),
                ('site_keywords', models.TextField(default='machine learning, AI, portfolio, python, tensorflow, data science', help_text='SEO keywords (comma-separated)')),
                ('primary_color', models.CharField(default='#00f6ff', help_text='Primary cyan color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#1effc6', help_text='Neural green color (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#b97aff', help_text='Soft violet color (hex format)', max_length=7)),
                ('show_social_links', models.BooleanField(default=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics measurement ID', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to show during maintenance')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(help_text='Skill level percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('icon', models.CharField(default='💻', help_text='Emoji icon for the skill', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description of your experience with this skill')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of experience with this skill')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured skills section')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00f6ff', help_text='Category color for UI (hex format)', max_length=7)),
                ('icon', models.CharField(default='🔧', help_text='Emoji icon for the category', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brief project description')),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed project description')),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('demo_url', models.URLField(blank=True, help_text='Demo or documentation URL', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Main project image (recommended: 800x600px)', null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured projects section')),
                ('is_active', models.BooleanField(default=True, help_text='Display on website')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.projectcategory')),
                ('technologies', models.ManyToManyField(help_text='Technologies/skills used in this project', related_name='projects', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'category')},
        ),
    ]
